// Production of Samuel.M.K also know as T756-Tech
"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "./FeaturesSection.module.css";

// Import local images from the Unsplash folder
import twinImg from "../../Feature Images/conny-schneider-xuTJZ7uD7PI-unsplash.jpg";
import aiOpsImg from "../../Feature Images/scott-rodgerson-PSpf_XgOM5w-unsplash.jpg";
import predictImg from "../../Feature Images/claudio-schwarz-fyeOxvYvIyY-unsplash.jpg";
import analyticsImg from "../../Feature Images/zuriel-forcades-zf-j-r-W-mXjz9YVRs-unsplash.jpg";

const features = [
    {
        id: "twin",
        title: "Digital Twin Engine",
        boldPrefix: "Live synchronization with physical infrastructure.",
        description: "Our engine pulls telemetry to create a pixel-perfect conceptual replica of your topology. Instantly identify bottlenecks, inspect individual tower metrics, and trace packet loss back to hardware failures.",
        image: twinImg,
        href: "/dashboard/twin"
    },
    {
        id: "aiops",
        title: "AI Operations",
        boldPrefix: "Autonomous routing optimizations.",
        description: "Let Mistral AI continuously analyze macroscopic traffic patterns. It creates a living knowledge base that predicts and autonomously resolves congestion before users notice a drop in service.",
        image: aiOpsImg,
        href: "/dashboard/ai-ops"
    },
    {
        id: "predictions",
        title: "Scenario Predictions",
        boldPrefix: "Prepare for the unpredictable.",
        description: "Safely fork your production database into a simulated environment to test the impact of future events—from massive sporting events to extreme weather outages, generating precise risk heatmaps.",
        image: predictImg,
        href: "/dashboard/predictions"
    },
    {
        id: "analytics",
        title: "Enterprise Analytics",
        boldPrefix: "Real-time financial impact tracking.",
        description: "Prove your ROI with comprehensive BI dashboards tracking 24-hour utilization trends, mapping hardware faults, and directly calculating the financial savings generated by automated AI decisions.",
        image: analyticsImg,
        href: "/dashboard/analytics"
    }
];

export default function FeaturesSection() {
    const [activeIndex, setActiveIndex] = useState(0);
    const activeFeature = features[activeIndex];

    const handleNext = () => {
        setActiveIndex((prev) => Math.min(prev + 1, features.length - 1));
    };

    const handlePrev = () => {
        setActiveIndex((prev) => Math.max(prev - 1, 0));
    };

    return (
        <section id="features" className={styles.container}>
            {/* Top Header & Controls */}
            <div className={styles.header}>
                <div className={styles.headerText}>
                    <h2 className={styles.title}>Platform Capabilities</h2>
                    <p className={styles.subtitle}>Explore the NetTwin architecture.</p>
                </div>
                <div className={styles.controls}>
                    <button
                        className={styles.arrowBtn}
                        onClick={handlePrev}
                        disabled={activeIndex === 0}
                        aria-label="Previous feature"
                    >
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m15 18-6-6 6-6" /></svg>
                    </button>
                    <button
                        className={styles.arrowBtn}
                        onClick={handleNext}
                        disabled={activeIndex === features.length - 1}
                        aria-label="Next feature"
                    >
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6" /></svg>
                    </button>
                </div>
            </div>

            {/* Horizontal Accordion Carousel */}
            <div className={styles.carousel}>
                {features.map((feature, idx) => {
                    const isActive = activeIndex === idx;
                    return (
                        <div
                            key={feature.id}
                            className={`${styles.card} ${isActive ? styles.cardActive : ''}`}
                            onClick={() => setActiveIndex(idx)}
                        >
                            <Image
                                src={feature.image}
                                alt={feature.title}
                                className={styles.cardImage}
                                priority={idx === 0}
                                placeholder="blur"
                            />
                            {/* Dark gradient for text readability */}
                            <div className={styles.cardGradient}></div>
                            {/* Feature Title overlays on image when active */}
                            <h3 className={styles.cardTitle}>{feature.title}</h3>
                        </div>
                    );
                })}
            </div>

            {/* Changing Details Section */}
            {/* The 'key' ensures the animation triggers when the feature changes */}
            <div className={styles.details} key={activeFeature.id}>
                <p className={styles.detailsText}>
                    <strong>{activeFeature.boldPrefix}</strong> {activeFeature.description}
                </p>
                <div className={styles.detailsAction}>
                    <Link href="/about" className={styles.readBtn}>
                        About us
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6" /></svg>
                    </Link>
                </div>
            </div>
        </section>
    );
}
